FROM node:20-alpine

# Set the working directory
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Expose Vite's default port
EXPOSE 5173


CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
